swagger: '2.0'

info:
  version: "0.0.0"
  title: Nyancast API
tags:
  - name: podcast
    description: Operations about podcasts
  - name: episode
    description: Operations about podcasts' episodes
  - name: user
    description: Operations about user
paths:
  /search:
    get:
      tags:
        - podcast
      summary: Query Itunes search API and return found podcasts
      parameters:
        -
          name: q
          in: query
          description: Search terms
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/PodcastList'
        204:
          description: No results
        400:
          description: Missing q parameter
        503:
          description: Problem contacting Itunes search API

  /podcast/{id}:
    get:
      tags:
        - podcast
      summary: Get informations about a podcast
      description: |
        This can trigger an Itunes request if the podcast doesn't exists in the local database.
        Property "isSubscribed" is only present in response when user is logged in
      parameters:
        -
          name: id
          in: path
          description: Itunes podcast id
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Podcast'
        400:
          description: Missing/wrong parameter id
        404:
          description: No podcast found for specified id
        503:
          description: Problem contacting Itunes search API

  /podcast/{id}/episodes:
    get:
      tags:
        - podcast
      summary: Get episodes of a podcast
      description: |
        By default, the latest 20 episodes (if available) are sent to the client.
        Property "isPlayed" is only present in response when user is logged in
      parameters:
        -
          name: id
          in: path
          description: Itunes podcast id
          required: true
          type: integer
        -
          name: p
          in: query
          description: Page
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              moreToLoad:
                type: boolean
              episodes:
                type: array
                items:
                  $ref: '#/definitions/Episode'
        400:
          description: Missing/wrong parameter id
        404:
          description: No podcast found for specified id

  /podcast/{id}/subscribe:
    post:
      tags:
        - podcast
      summary: Subscribe a user to a podcast
      parameters:
        -
          name: id
          in: path
          description: Itunes podcast id
          required: true
          type: integer
      responses:
        200:
          description: Subscription successful
        304:
          description: User is already subscribed to the podcast
        400:
          description: Missing/wrong parameter id
        401:
          description: User is not logged in
        404:
          description: No podcast found for specified id

  /podcast/{id}/unsubscribe:
    post:
      tags:
        - podcast
      summary: Unsubscribe a user to a podcast
      parameters:
        -
          name: id
          in: path
          description: Itunes podcast id
          required: true
          type: integer
      responses:
        200:
          description: Unsubscription successful
        304:
          description: User is not subscribed to the podcast
        400:
          description: Missing/wrong parameter id
        401:
          description: User is not logged in
        404:
          description: No podcast found for specified id

  /episode/{id}/update_status:
    post:
      tags:
        - episode
      summary: Update playing status of an episode
      description: |
        User have to be logged in, and subscribed to the episodes' podcast.
        Parameter status can be either "played" or "unplayed"
      parameters:
        -
          name: id
          in: path
          description: Episode id
          required: true
          type: integer
        - 
          name: status
          in: query
          description: New playing status
          required: true
          type: string
      responses:
        200:
          description: Status update successful
        304:
          description: Status unchanged
        400:
          description: Missing/wrong parameters, or user not subscribed to podcast
        401:
          description: User is not logged in
        404:
          description: No episode found for specified id
        

  /user/subscriptions:
    get:
      tags:
        - user
      summary: Get list of podcasts the user is subscribed to
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/PodcastList'
        204:
          description: No subscriptions
        401:
          description: User is not logged in

  /user:
    get:
      tags:
        - user
      summary: Get the current user
      responses:
        200:
          description: Successful response
        401:
          description: User is not logged in
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /signup:
    post:
      tags:
        - user
      summary: Create a new user
      parameters:
        -
          name: username
          in: query
          description: Username must be greater or equals to 4
          required: true
          type: string
        -
          name: password
          in: query
          description: Password must be greater or equals to 8
          required: true
          type: string
      responses:
        200:
          description: Successful response. New user has been created
        400:
          description: Missing/wrong parameter (username/password)
        409:
          description: Username is already used

  /logout:
    post:
      tags:
        - user
      summary: Log out user
      responses:
        200:
          description: Successful response. User is log out

  /login:
    post:
      tags:
        - user
      summary: Log in user
      parameters:
        -
          name: username
          in: query
          required: true
          type: string
        -
          name: password
          in: query
          required: true
          type: string
      responses:
        200:
          description: Successful response. User is connected
        403:
          description: Username/password are invalid

definitions:
  PodcastList:
    type: object
    properties:
      itunesId:
        type: integer
      title:
        type: string
      author:
        type: string
      thumbnailURL:
        type: string

  Podcast:
    type: object
    properties:
      itunesId:
        type: integer
      title:
        type: string
      author:
        type: string
      thumbnailURL:
        type: string
      description:
        type: string
      websiteURL:
        type: string
      isSubscribed:
        type: boolean

  Episode:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      fileURL:
        type: string
      description:
        type: string
      date:
        type: string
      isPlayed:
        type: boolean
        

  User:
    type: object
    properties:
      username:
        type: string
